name: toyota-fan-site
services:
  web:
    restart: always
    build: 
      context: .
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - ./.env
  proxy:
    restart: always
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
